[build-system]
requires = [
  "setuptools>=48",
]
build-backend = "setuptools.build_meta"

[project]
name = "vllm-openvino"
description = "OpenVINO plugin for vLLM"
readme = "README.md"
license = {text = "Apache-2.0"}
version = "0.19.1"
authors = [
    {name = "belonghim"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "openvino >= 2026.1.0",
    "vllm == 0.19.1",
]
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/belonghim/vllm-openvino"
Repository = "https://github.com/belonghim/vllm-openvino"

[project.entry-points."vllm.platform_plugins"]
openvino = "vllm_openvino:register"

[tool.setuptools.packages.find]
where = ["."]  # list of folders that contain the packages (["."] by default)
include = ["vllm_openvino*"]  # package names should match these glob patterns (["*"] by default)
exclude = []  # exclude packages matching these glob patterns (empty by default)
namespaces = false  # to disable scanning PEP 420 namespaces (true by default)



